Readme og litt automatisering av py->ipynb->md
statisticsnorway/ssb-gis-utils pull request #21
Opened 2023-02-27 09:04 UTC by mortewle

Fortsatt litt stygg jupyter-output som enten kan fjernes manuelt eller noe automatisk find-replace. Eller få lagt til de css-greiene som gjør det fint i ipynb.

2023-02-27 20:15 UTC, arneso-ssb commented
@mortewle README.md-filen blir fryktelig lang og detaljert nå. Det du har lagt til i toppen av README.md foreslår jeg at du legger i et annet markdown-dokument, og at du reverterer endringen i README.md. Eventuelt at du linker til den nye beskrivelsen fra README.md.

2023-02-28 22:15 UTC, arneso-ssb requested changes
Litt småting å rette på, se kommentarer i filer. Bare spør hvis du lurer på noe av det.
Husk også den første kommentaren min om å revertere README.md.

2023-02-28 22:15 UTC, arneso-ssb commented on tests/network_analysis_examples.py
> +#       format_name: light
Bruk percent-format når du lagrer Notebooks.  Trengs for at isort skal håndtere sortering av importer riktig i slike filer, med opsjonen` treat_comments_as_code = ["# %%"]`.

2023-02-28 22:15 UTC, arneso-ssb commented on tests/network_analysis_demo_template.py
> +#       format_name: light
Bruk percent-format når du lagrer Notebooks.  Trengs for at isort skal håndtere sortering av importer riktig i slike filer, med opsjonen` treat_comments_as_code = ["# %%"]`.

2023-03-01 00:25 UTC, mortewle commented on src/gis_utils/points.py
>              nodes, rules, from_col="temp_idx", to_col="node_id"
Her er det ingen fornuftige defaultverdier, siden verdiene er motsatt for Origins og Destinations. Og det ville vel uansett vært brudd på nr 1 i det som ikke er lov? Men ser poenget. Da kan jeg like gjerne droppe metodene i subklassene, og heller bruke to ekstra parametre når metoden kalles.

2023-03-01 00:43 UTC, mortewle commented on src/gis_utils/network_functions.py
> +jupyter nbconvert --to markdown tests/examples.ipynb --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_cell_tags remove_cell
Ja, det var noen terminalkommandoer jeg har glemt å fjerne

2023-03-01 01:00 UTC, mortewle commented on src/gis_utils/directednetwork.py
> +    Attributes:
Kan høres ut som det der er snakk om bare Args, ikke Attributes? Det er det Google foreslår, ser jeg.

2023-03-01 01:09 UTC, mortewle commented
> @mortewle README.md-filen blir fryktelig lang og detaljert nå. Det du har lagt til i toppen av README.md foreslår jeg at du legger i et annet markdown-dokument, og at du reverterer endringen i README.md. Eventuelt at du linker til den nye beskrivelsen fra README.md.

Ja, kan kutte ned readme. Skal heller få inn noen eksempler i analyseclassen. Men der kan man ikke ha kart, så hadde vært fint med det i readme. Geopandas’ readme har fire store kart.

2023-03-01 10:19 UTC, arneso-ssb commented on src/gis_utils/directednetwork.py
> +    Attributes:
Ja, greit med bare Args.

2023-03-03 06:43 UTC, arneso-ssb approved these changes

2023-03-03 06:44 UTC, merged