Eksempler i docstring, litt i tester
statisticsnorway/ssb-gis-utils pull request #34
Opened 2023-03-03 14:47 UTC by mortewle

2023-03-05 08:45 UTC, arneso-ssb requested changes
Alt er greit i denne pull requesten, bortsett fra en ting: src-pakka skal ikke ha noen avhengigheter eller referanser til noe som har med test å gjøre. De konkrete kommentarene i filene er alle relaterte til dette.

2023-03-05 08:45 UTC, arneso-ssb commented on src/gis_utils/__init__.py
> +roadpath = (
Src-pakken skal ikke inneholde noe om testdata og tester, så fjern alt som har med det å gjøre fra `__init__.py`. Src-pakker skal aldri ha avhengigheter til tester, blant annet fordi ellers vil testavhengighetene bli pakkeavhengigheter. I utgangspunkte skal `__init_.py` bare refere til ting i `gis_utils` og eventuelt kode som er nødvendig å kjøre når man importerer pakken.

2023-03-05 08:45 UTC, arneso-ssb commented on tests/conftest.py
> +from gis_utils import testgdf
Se tidligere kommentar om at gis_utils ikke skal inneholde noe om test. Rett opp denne importen etter fjerning av test-ting fra `__init__.py`.

2023-03-05 08:45 UTC, arneso-ssb commented on tests/test_network_analysis.py
> +    p = gpd.read_parquet(gs.pointpath)
"Undo" denne endringen. ref tidligere kommentar om at src-pakken ikke skal inneholde noe om test. Eller alternativt flytt definsjonen av pointpath og roadpath til conftest.py (som fixture), og definer testfunksjonen som:
`def test_network_analysis(pointpath, roadpath):`
Da er disse variablene automatisk tilgjengelig i funksjonen.

2023-03-05 08:45 UTC, arneso-ssb commented on tests/test_network_analysis.py
> +    r = gpd.read_parquet(gs.roadpath)
Se kommentar ovenfor.

2023-03-05 08:45 UTC, arneso-ssb commented on tests/test_network_methods.py
> +    p = gpd.read_parquet(gs.pointpath)
Se kommentarer på test_network_analysis.py.

2023-03-05 08:45 UTC, arneso-ssb commented on tests/test_node_ids.py
> +    p = gpd.read_parquet(gs.pointpath)
Se kommentar på test_network_analysis.py.

2023-03-05 19:42 UTC, mortewle commented
@arneso-ssb Disse variablene i __init__ var egentlig ikke ment for testing, men utforsking, ikke bare for min del. Hva med å flytte testdataene ut av testmappa? Veldig praktisk å ha noe eksempeldata uten å måtte skrive hele stien. Flere python-pakker som har det, blant annet geopandas.

https://stackoverflow.com/questions/28417293/sample-datasets-in-pandas
https://github.com/geopandas/geopandas/tree/main/geopandas/datasets

2023-03-10 14:03 UTC, arneso-ssb approved these changes

2023-03-10 14:03 UTC, merged