Finner ikke pakka
statisticsnorway/ssb-gis-utils pull request #9
Opened 2023-02-20 10:00 UTC by mortewle

Burde ikke gis_utils kunne importeres i testfilene? Får det bare til med sys.path.append til src-mappa.

src = str(Path(__file__).parent).strip("tests") + "src"

sys.path.append(src)

import gis_utils as gs

2023-02-22 13:34 UTC, arneso-ssb requested changes
Har en del konkrete kommentarer i filene, og en generell:
- Fila `demo.py` foreslår jeg at du døper om til `demo_template.py`. Dette for å synliggjøre at det ikke er en vanlig .py fil. Gjøres med kommando `git mv`

2023-02-22 13:34 UTC, arneso-ssb commented on src/gis_utils/dapla.py
Importer skal være i toppen av file, i følge PEP8. Legg til:
-  `from dapla import Fileclient, details`
- `import os`

2023-02-22 13:34 UTC, arneso-ssb commented on src/gis_utils/dapla.py
>          from dapla import details
Fjern import i funksjonen, ref kommentar lenger opp.

2023-02-22 13:34 UTC, arneso-ssb commented on src/gis_utils/dapla.py
Linje 16: Fjern import i funksjonen, ref kommentar lenger opp
Linje 18: `exists` er det samme som navnet på funksjonen. Bruk `return os.path.exists(path)` i stedet.

2023-02-22 13:34 UTC, arneso-ssb commented on src/gis_utils/dapla.py
> -    from pyarrow import parquet
Fjern importer i funksjonen, ref kommentar lenger opp.

2023-02-22 13:34 UTC, arneso-ssb commented on src/gis_utils/dapla.py
>  def lag_mappe(sti):
Bytt til engelsk navn på funksjonen.

2023-02-22 13:34 UTC, arneso-ssb commented on src/gis_utils/dapla.py
>  def samle_filer(filer: list, **kwargs) -> gpd.GeoDataFrame:
Bytt til engelsk navn på funksjonen.

2023-02-22 13:34 UTC, arneso-ssb commented on src/gis_utils/dapla.py
>          from os import makedirs
Fjern  importer i funksjonen, ref kommentar lenger opp.

2023-02-22 14:10 UTC, mortewle commented
Endra til importer i toppen, men ikke dapla-importene. Disse funksjonene passer jo egentlig bedre i dapla-toolbelt. 

Ellers har jeg nå en clean demo.md, men den er avhengig av en demo.ipynb. Kan det være mulig å beholde en nbstrippet demo.ipynb heller enn demo_template.py?

2023-02-23 08:04 UTC, arneso-ssb commented on src/gis_utils/dapla.py
@mortewle Ja, enig i det. Spørsmålet er egentlig om funksjonene read_geopandas og write_geopandas trenger å skrive til bøtter på dapla? Hvis ja, så må avhengigheten være der, siden koden bruker dapla-toolbelt og ikke vil virke uten at dapla-toolbelt er importert. Man kan alternativt ha det som en extras dependency, ala `poetry install ssb-gis-utils[dapla]` som beskrevet [her](https://python-poetry.org/docs/pyproject/#extras).

Et annen ting å vurdere er om koden kanskje burde sjekke om den kjører på dapla eller ikke (jeg har kode for dette), og skrive til vanlig filsti hvis den ikke kjører på dapla, og skrive til dapla-bøtter hvis den gjør det. Vi kan diskutere dette mer i morgen, og la det det være slik det er nå inntil videre.

2023-02-23 08:10 UTC, arneso-ssb commented
> Ellers har jeg nå en clean demo.md, men den er avhengig av en demo.ipynb. Kan det være mulig å beholde en nbstrippet demo.ipynb heller enn demo_template.py?

Eller begge deler? Kodekvalitetsverktøy vil ikke kunne sjekke koden i demo.ipynb. Vi kan diskutere dette mer i morgen. Jeg godkjenner nå, og så ser vi på de småtingene vi har vært inne på her i morgen.

2023-02-23 08:11 UTC, arneso-ssb approved these changes

2023-02-23 08:11 UTC, merged